"""empty message

Revision ID: 1383c4d35bca
Revises: 829d451ecbb7
Create Date: 2025-12-02 14:26:49.174332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1383c4d35bca'
down_revision = '829d451ecbb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallax_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.drop_column('parallax_image')

    # ### end Alembic commands ###
