"""empty message

Revision ID: 207edeebba79
Revises: 23c2219dc82e
Create Date: 2025-12-15 03:30:24.511370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207edeebba79'
down_revision = '23c2219dc82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('getoffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider', sa.String(length=50), nullable=True),
    sa.Column('getoffer_form_id', sa.Integer(), nullable=True),
    sa.Column('getoffer_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['getoffer_form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('getoffer')
    # ### end Alembic commands ###
