"""empty message

Revision ID: 23c2219dc82e
Revises: d650ca1dcfb6
Create Date: 2025-12-13 21:10:47.169300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c2219dc82e'
down_revision = 'd650ca1dcfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('form_key', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=150), nullable=True),
    sa.Column('submit_btn_text', sa.String(length=50), nullable=True),
    sa.Column('success_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_key')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider', sa.String(length=50), nullable=True),
    sa.Column('contact_form_id', sa.Integer(), nullable=True),
    sa.Column('contact_info_title', sa.String(length=200), nullable=True),
    sa.Column('shop_id', sa.String(length=200), nullable=True),
    sa.Column('shop_id_date', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('wa', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('workhours', sa.String(length=200), nullable=True),
    sa.Column('location_shop', sa.String(length=200), nullable=True),
    sa.Column('location_storage', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['contact_form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=True),
    sa.Column('placeholder', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submission_data', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_submissions')
    op.drop_table('form_fields')
    op.drop_table('contact')
    op.drop_table('forms')
    # ### end Alembic commands ###
