"""empty message

Revision ID: 2a4730cb71b6
Revises: 1383c4d35bca
Create Date: 2025-12-02 14:33:28.412649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4730cb71b6'
down_revision = '1383c4d35bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.alter_column('parallax_subtitle',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.alter_column('parallax_subtitle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
