"""Service model updated

Revision ID: 5510221b3039
Revises: 12ad24207b5e
Create Date: 2026-01-03 15:17:47.579037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5510221b3039'
down_revision = '12ad24207b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('slider_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('features_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_btn_text', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('detail_image_path', sa.String(length=200), nullable=True))
        batch_op.create_foreign_key('fk_services_slider_group', 'slider_groups', ['slider_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('detail_image_path')
        batch_op.drop_column('description_title')
        batch_op.drop_column('video_url')
        batch_op.drop_column('video_btn_text')
        batch_op.drop_column('features')
        batch_op.drop_column('features_title')
        batch_op.drop_column('slider_group_id')
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
