"""empty message

Revision ID: 642d4e1418d8
Revises: c3f84be05ac9
Create Date: 2025-12-04 23:37:23.498596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642d4e1418d8'
down_revision = 'c3f84be05ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_slider', sa.String(length=50), nullable=True))
        batch_op.drop_column('herocta_action_url')
        batch_op.drop_column('herocta_action02_text')
        batch_op.drop_column('herocta_title')
        batch_op.drop_column('herocta_action_text')
        batch_op.drop_column('herocta_subtitle')
        batch_op.drop_column('hero_image')
        batch_op.drop_column('herocta_action02_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('herocta_action02_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('herocta_subtitle', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('herocta_action_text', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('herocta_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('herocta_action02_text', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('herocta_action_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('hero_slider')

    # ### end Alembic commands ###
