"""empty message

Revision ID: 6476554f2de9
Revises: 91ad81636092
Create Date: 2026-01-10 11:14:04.375383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476554f2de9'
down_revision = '91ad81636092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_group_2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_group_3_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'slider_groups', ['slider_group_2_id'], ['id'])
        batch_op.create_foreign_key(None, 'slider_groups', ['slider_group_3_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('slider_group_3_id')
        batch_op.drop_column('slider_group_2_id')

    # ### end Alembic commands ###
