"""empty message

Revision ID: 6480f6bfe8ae
Revises: 2a4730cb71b6
Create Date: 2025-12-02 22:52:21.033016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6480f6bfe8ae'
down_revision = '2a4730cb71b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_title_bold', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cta_title_light', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cta_intro_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cta_btn_text', sa.String(length=200), nullable=True))
        batch_op.drop_column('cta_badge')
        batch_op.drop_column('cta_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cta_badge', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('cta_btn_text')
        batch_op.drop_column('cta_intro_text')
        batch_op.drop_column('cta_title_light')
        batch_op.drop_column('cta_title_bold')

    # ### end Alembic commands ###
