"""empty message

Revision ID: 78d430fd67d1
Revises: 9a6820b21cf1
Create Date: 2025-12-11 05:56:40.077162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d430fd67d1'
down_revision = '9a6820b21cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider', sa.String(length=50), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('corporate_slider', sa.String(length=50), nullable=True),
    sa.Column('personal_slider', sa.String(length=50), nullable=True),
    sa.Column('parallax_title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('references')
    # ### end Alembic commands ###
