"""empty message

Revision ID: 829d451ecbb7
Revises: 97f6a240ea1e
Create Date: 2025-12-02 14:19:40.571888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829d451ecbb7'
down_revision = '97f6a240ea1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallax_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parallax_subtitle', sa.String(length=300), nullable=True))
        batch_op.drop_column('products_subtitle')
        batch_op.drop_column('products_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('products_subtitle', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('parallax_subtitle')
        batch_op.drop_column('parallax_title')

    # ### end Alembic commands ###
