"""Initial migration

Revision ID: 97f6a240ea1e
Revises: 
Create Date: 2025-12-02 02:09:44.147695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f6a240ea1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_image', sa.String(length=200), nullable=True),
    sa.Column('herocta_title', sa.String(length=200), nullable=True),
    sa.Column('herocta_subtitle', sa.Text(), nullable=True),
    sa.Column('herocta_action_text', sa.String(length=50), nullable=True),
    sa.Column('herocta_action_url', sa.String(length=200), nullable=True),
    sa.Column('herocta_action02_text', sa.String(length=50), nullable=True),
    sa.Column('herocta_action02_url', sa.String(length=200), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('presentation_subtitle', sa.Text(), nullable=True),
    sa.Column('presentation_action_text', sa.String(length=50), nullable=True),
    sa.Column('presentation_action_url', sa.String(length=200), nullable=True),
    sa.Column('features_title', sa.String(length=200), nullable=True),
    sa.Column('features_subtitle', sa.Text(), nullable=True),
    sa.Column('products_title', sa.String(length=200), nullable=True),
    sa.Column('products_subtitle', sa.String(length=100), nullable=True),
    sa.Column('cta_badge', sa.String(length=100), nullable=True),
    sa.Column('cta_title', sa.String(length=200), nullable=True),
    sa.Column('cta_description', sa.Text(), nullable=True),
    sa.Column('cta_image', sa.String(length=200), nullable=True),
    sa.Column('partnership_title', sa.String(length=200), nullable=True),
    sa.Column('partnership_desc', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('action_text', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_specs', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=150), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('meta_keywords', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('favicon_path', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key')
    )
    op.create_table('products_services',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'service_id')
    )
    op.create_table('slider_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['slider_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_item')
    op.drop_table('products_services')
    op.drop_table('slider_group')
    op.drop_table('site_setting')
    op.drop_table('service')
    op.drop_table('product')
    op.drop_table('menu_item')
    op.drop_table('home_config')
    # ### end Alembic commands ###
