"""empty message

Revision ID: 98c0659e2e85
Revises: 42ee3600d027
Create Date: 2025-12-03 01:48:45.052582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c0659e2e85'
down_revision = '42ee3600d027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slider_select', sa.String(length=50), nullable=True))
        batch_op.drop_column('partnership_desc')
        batch_op.drop_column('partnership_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partnership_title', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('partnership_desc', sa.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('slider_select')
        batch_op.drop_column('slider_description')

    # ### end Alembic commands ###
