"""empty message

Revision ID: 9a6820b21cf1
Revises: 642d4e1418d8
Create Date: 2025-12-10 03:01:14.653002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6820b21cf1'
down_revision = '642d4e1418d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider', sa.String(length=50), nullable=True),
    sa.Column('presentation_slider', sa.String(length=50), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('howeare', sa.Text(), nullable=True),
    sa.Column('whatwedo', sa.Text(), nullable=True),
    sa.Column('whyus', sa.Text(), nullable=True),
    sa.Column('card01_title', sa.String(length=200), nullable=True),
    sa.Column('card01_subtitle', sa.Text(), nullable=True),
    sa.Column('card02_title', sa.String(length=200), nullable=True),
    sa.Column('card02_subtitle', sa.Text(), nullable=True),
    sa.Column('card03_title', sa.String(length=200), nullable=True),
    sa.Column('card03_subtitle', sa.Text(), nullable=True),
    sa.Column('card04_title', sa.String(length=200), nullable=True),
    sa.Column('card04_subtitle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corporate')
    # ### end Alembic commands ###
