"""empty message

Revision ID: c3f84be05ac9
Revises: 98c0659e2e85
Create Date: 2025-12-04 06:15:46.905380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f84be05ac9'
down_revision = '98c0659e2e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link01_text', sa.String(length=50), nullable=True),
    sa.Column('link01_url', sa.String(length=200), nullable=True),
    sa.Column('link02_text', sa.String(length=50), nullable=True),
    sa.Column('link02_url', sa.String(length=200), nullable=True),
    sa.Column('link03_text', sa.String(length=50), nullable=True),
    sa.Column('link03_url', sa.String(length=200), nullable=True),
    sa.Column('link04_text', sa.String(length=50), nullable=True),
    sa.Column('link04_url', sa.String(length=200), nullable=True),
    sa.Column('link05_text', sa.String(length=50), nullable=True),
    sa.Column('link05_url', sa.String(length=200), nullable=True),
    sa.Column('shop_address', sa.String(length=200), nullable=True),
    sa.Column('storage_address', sa.String(length=200), nullable=True),
    sa.Column('shop_tel', sa.String(length=50), nullable=True),
    sa.Column('mobile_tel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('policy_text', sa.String(length=50), nullable=True),
    sa.Column('policy_url', sa.String(length=200), nullable=True),
    sa.Column('kvkk_text', sa.String(length=50), nullable=True),
    sa.Column('kvkk_url', sa.String(length=200), nullable=True),
    sa.Column('cookies_text', sa.String(length=50), nullable=True),
    sa.Column('cookies_url', sa.String(length=200), nullable=True),
    sa.Column('copyright', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('footer')
    # ### end Alembic commands ###
