"""empty message

Revision ID: d650ca1dcfb6
Revises: 78d430fd67d1
Create Date: 2025-12-12 02:57:42.769999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd650ca1dcfb6'
down_revision = '78d430fd67d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parallax_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_column('parallax_image')

    # ### end Alembic commands ###
