"""Modeller guncellendi

Revision ID: ffd5964cad61
Revises: 
Create Date: 2025-12-17 08:09:51.795824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd5964cad61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link01_text', sa.String(length=50), nullable=True),
    sa.Column('link01_url', sa.String(length=200), nullable=True),
    sa.Column('link02_text', sa.String(length=50), nullable=True),
    sa.Column('link02_url', sa.String(length=200), nullable=True),
    sa.Column('link03_text', sa.String(length=50), nullable=True),
    sa.Column('link03_url', sa.String(length=200), nullable=True),
    sa.Column('link04_text', sa.String(length=50), nullable=True),
    sa.Column('link04_url', sa.String(length=200), nullable=True),
    sa.Column('link05_text', sa.String(length=50), nullable=True),
    sa.Column('link05_url', sa.String(length=200), nullable=True),
    sa.Column('shop_address', sa.Text(), nullable=True),
    sa.Column('storage_address', sa.Text(), nullable=True),
    sa.Column('shop_tel', sa.String(length=50), nullable=True),
    sa.Column('mobile_tel', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('policy_text', sa.String(length=50), nullable=True),
    sa.Column('policy_url', sa.String(length=200), nullable=True),
    sa.Column('kvkk_text', sa.String(length=50), nullable=True),
    sa.Column('kvkk_url', sa.String(length=200), nullable=True),
    sa.Column('cookies_text', sa.String(length=50), nullable=True),
    sa.Column('cookies_url', sa.String(length=200), nullable=True),
    sa.Column('copyright', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('form_key', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=150), nullable=True),
    sa.Column('submit_btn_text', sa.String(length=50), nullable=True),
    sa.Column('success_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_key')
    )
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('action_text', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_specs', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=150), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('meta_keywords', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=200), nullable=True),
    sa.Column('favicon_path', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_key', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_key')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider_id', sa.Integer(), nullable=True),
    sa.Column('contact_form_id', sa.Integer(), nullable=True),
    sa.Column('contact_info_title', sa.String(length=200), nullable=True),
    sa.Column('shop_id', sa.String(length=200), nullable=True),
    sa.Column('shop_id_date', sa.String(length=200), nullable=True),
    sa.Column('tax_id', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('wa', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('workhours', sa.String(length=200), nullable=True),
    sa.Column('location_shop', sa.String(length=200), nullable=True),
    sa.Column('location_storage', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['contact_form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['hero_slider_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider_id', sa.Integer(), nullable=True),
    sa.Column('presentation_slider_id', sa.Integer(), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('howeare', sa.Text(), nullable=True),
    sa.Column('whatwedo', sa.Text(), nullable=True),
    sa.Column('whyus', sa.Text(), nullable=True),
    sa.Column('card01_title', sa.String(length=200), nullable=True),
    sa.Column('card01_subtitle', sa.Text(), nullable=True),
    sa.Column('card02_title', sa.String(length=200), nullable=True),
    sa.Column('card02_subtitle', sa.Text(), nullable=True),
    sa.Column('card03_title', sa.String(length=200), nullable=True),
    sa.Column('card03_subtitle', sa.Text(), nullable=True),
    sa.Column('card04_title', sa.String(length=200), nullable=True),
    sa.Column('card04_subtitle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hero_slider_id'], ['slider_groups.id'], ),
    sa.ForeignKeyConstraint(['presentation_slider_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=True),
    sa.Column('placeholder', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submission_data', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('getoffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider_id', sa.Integer(), nullable=True),
    sa.Column('getoffer_form_id', sa.Integer(), nullable=True),
    sa.Column('getoffer_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['getoffer_form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['hero_slider_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider_id', sa.Integer(), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('presentation_subtitle', sa.Text(), nullable=True),
    sa.Column('presentation_action_text', sa.String(length=50), nullable=True),
    sa.Column('presentation_action_url', sa.String(length=200), nullable=True),
    sa.Column('features_title', sa.String(length=200), nullable=True),
    sa.Column('features_subtitle', sa.Text(), nullable=True),
    sa.Column('parallax_title', sa.String(length=200), nullable=True),
    sa.Column('parallax_subtitle', sa.Text(), nullable=True),
    sa.Column('parallax_image', sa.String(length=200), nullable=True),
    sa.Column('cta_title_bold', sa.String(length=100), nullable=True),
    sa.Column('cta_title_light', sa.String(length=200), nullable=True),
    sa.Column('cta_intro_text', sa.Text(), nullable=True),
    sa.Column('cta_btn_text', sa.String(length=200), nullable=True),
    sa.Column('cta_description', sa.Text(), nullable=True),
    sa.Column('cta_image', sa.String(length=200), nullable=True),
    sa.Column('slider_description', sa.Text(), nullable=True),
    sa.Column('slider_select_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_slider_id'], ['slider_groups.id'], ),
    sa.ForeignKeyConstraint(['slider_select_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_services',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'service_id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_slider_id', sa.Integer(), nullable=True),
    sa.Column('presentation_title', sa.String(length=200), nullable=True),
    sa.Column('corporate_slider_id', sa.Integer(), nullable=True),
    sa.Column('personal_slider_id', sa.Integer(), nullable=True),
    sa.Column('parallax_image', sa.String(length=200), nullable=True),
    sa.Column('parallax_title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['corporate_slider_id'], ['slider_groups.id'], ),
    sa.ForeignKeyConstraint(['hero_slider_id'], ['slider_groups.id'], ),
    sa.ForeignKeyConstraint(['personal_slider_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slider_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('btn_text', sa.String(length=50), nullable=True),
    sa.Column('btn_link', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['slider_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_items')
    op.drop_table('references')
    op.drop_table('products_services')
    op.drop_table('home_config')
    op.drop_table('getoffer')
    op.drop_table('form_submissions')
    op.drop_table('form_fields')
    op.drop_table('corporate')
    op.drop_table('contact')
    op.drop_table('slider_groups')
    op.drop_table('site_setting')
    op.drop_table('service')
    op.drop_table('product')
    op.drop_table('menu_item')
    op.drop_table('forms')
    op.drop_table('footer')
    # ### end Alembic commands ###
